services:
  jobmanager:
    build: ./backend/
    image: echeryomushkin/clock_jobmanager
    command: "standalone-job --job-classname com.cheremushkin.ClockBackend"
    #     --fromSavepoint /tmp/flink-checkpoints-directory/1a67f2d385b2e2e9668feb8261644310/chk-14"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8081:8081
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/
      - ./flink/log:/opt/flink/log
      - ./backend/build:/backend
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq

  taskmanager:
    build: ./backend/
    image: echeryomushkin/clock_taskmanager
    depends_on:
      jobmanager:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/:rw
      - ./flink/log:/opt/flink/log:rw
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq
