services:
  frontend:
    build: ./app/
    
  rabbit: 
    build: ./rabbitmq/
  
  backendbuild:
    build: backend/
    image: flinkjar

  jobmanager:
    container_name: jobmanager_jar
    image: flinkjar
    depends_on:
      - backendbuild
    ports:
      - "8081:8081"
      - "6123:6123"
    command: standalone-job --job-classname com.cheremushkin.ClockBackend
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.adress: jobmanager
        jobmanager.web.log.path: /opt/flink/log/output.log
        parallelism.default: 1

  taskmanager:
    container_name: taskmanager_jar
    image: flinkjar
    depends_on:
      - backendbuild
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
        taskmanager.web.log.path: /opt/flink/log/output.log
        parallelism.default: 1
          
  flinkcliient:
    container_name: flinkclient_jar
    image: flinkjar
    depends_on:
      - backendbuild
      - rabbit
      - taskmanager
      - frontend
    command: flink run /opt/flink/usr/lib/worktask-backend-0.1-SNAPSHOT-all.jar

