services:
  frontend:
    build: ./app/
    ports:
      - 8080:80
    
  rabbitmq: 
    build: ./rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  backend:
    build: ./backend/
    command: "flink run -d /opt/ClockJob.jar --checkpointing --event-time --fromSavepoint /tmp/flink-savepoints/tm_172.20.0.537713-34535f"
    depends_on:
      jobmanager:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq

  jobmanager:
    image: apache/flink:1.17.1-scala_2.12-java11
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq

  taskmanager:
    image: apache/flink:1.17.1-scala_2.12-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq
