services:
  frontend:
    build: ./app/
    ports:
      - 8080:80
    
  rabbitmq: 
    build: ./rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  jobmanager:
    image: flink:1.17.1-scala_2.12-java11
    command: "jobmanager.sh start-foreground"
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 8081:8081
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/:rw
      - ./flink/log:/opt/flink/log:rw
      - ./backend/build/libs:/backend
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq

  taskmanager:
    image: flink:1.17.1-scala_2.12-java11
    depends_on:
      jobmanager:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./flink/conf:/opt/flink/conf
      - ./flink/data:/tmp/:rw
      - ./flink/log:/opt/flink/log:rw
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - RABBIT_HOST=rabbitmq
