services:
  clock-rabbit: 
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
