@startditaa EditCard

 +---------------+ 
 |card.component | 
 +---------------+
         | 
         v
+------------------+
| allow.service    |
|  edit_allowed {c}|
+------------------+
         | 
         v
 +---------------+
 |card.component | 
 |editing=true   |
 +---------------+
         | 
         v
 +---------------+
 |card.component | finish editing
 |editing=false  |-------------------+
 +---------------+                   | UPDATE_CARD_EVENT
         |                   +---------------+
         v                   |backend.service|
+------------------+         +---------------+
| allow.service    |
|  endEdit         |
+------------------+

@endditaa